<a href="https://colab.research.google.com/github/Data-Seyifunmi/Data-Cleaning-Projects/blob/main/July22_Class.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Read the csv file
import pandas as pd

In [2]:
# df means Data Frame
df = pd.read_csv("Jamb Result.csv")

In [3]:
# Check the structure of the table
# df.head will by default bring the first five of the table
df.head()

     Candidate_Name  English  Mathematics  Physics  Chemistry
0       Amina Nwosu       45           89       66         57
1  Oluwaseun Okafor       64           74       75         61
2      Tunde Okafor       50           48       61         75
3       Tunde Lawal       55           50       40         97
4      Paul Balogun       96           78       64         44

In [5]:
# You can specify the number of rows you want
df.head(3)

     Candidate_Name  English  Mathematics  Physics  Chemistry
0       Amina Nwosu       45           89       66         57
1  Oluwaseun Okafor       64           74       75         61
2      Tunde Okafor       50           48       61         75

In [6]:
df.head(10)

     Candidate_Name  English  Mathematics  Physics  Chemistry
0       Amina Nwosu       45           89       66         57
1  Oluwaseun Okafor       64           74       75         61
2      Tunde Okafor       50           48       61         75
3       Tunde Lawal       55           50       40         97
4      Paul Balogun       96           78       64         44
5     Adebayo Bello       86           68       46         97
6   Ifeanyi Balogun       82           49       48         90
7  Chinedu Akinyemi       98           67       76         70
8   Goodluck Nnamdi       93           42       89         59
9      Tunde Yakubu       91           70       53         92

In [7]:
# df.tail give the last 5 rows of the table by default
df.tail()

      Candidate_Name  English  Mathematics  Physics  Chemistry
1195    Emeka Nnamdi       82           47       44         92
1196     Tunde Okeke       65           79       86         60
1197      Adaobi Eze       59          100       48         86
1198  Ngozi Akinyemi       65           90       87         45
1199      Mary Lawal       61           86       85         46

In [10]:
# Adding the total and average column to the table
subject = ["English", "Mathematics", "Physics", "Chemistry"]
df["Total"] = df[subject].sum(axis=1)
# axis is equal to 1 because you are adding across the rows

In [11]:
df.head(3)

,Candidate_Name,English,Mathematics,Physics,Chemistry,Total,Total_Score
0,Amina Nwosu,45,89,66,57,257,257
1,Oluwaseun Okafor,64,74,75,61,274,274
2,Tunde Okafor,50,48,61,75,234,234

In [12]:
df.drop("Total_Score", axis=1, inplace = True)

In [13]:
df.head(3)

     Candidate_Name  English  Mathematics  Physics  Chemistry  Total
0       Amina Nwosu       45           89       66         57    257
1  Oluwaseun Okafor       64           74       75         61    274
2      Tunde Okafor       50           48       61         75    234

In [14]:
df["Average"] = df["Total"] / 4

In [15]:
df.head(3)

     Candidate_Name  English  Mathematics  Physics  Chemistry  Total  Average
0       Amina Nwosu       45           89       66         57    257    64.25
1  Oluwaseun Okafor       64           74       75         61    274    68.50
2      Tunde Okafor       50           48       61         75    234    58.50

In [19]:
foodstuffs = ["Rice", "Beans", "Gaari", "Yam", "Semo", "Pasta", "Bread"]
foodstuffs[0]
foodstuffs[-1]
# Slicing
foodstuffs[1:6]

['Beans', 'Gaari', 'Yam', 'Semo', 'Pasta']

In [20]:
# A situation where you have more then 4 subjects and you don't want to be writing the subject one after the other
# Use this method
# using "iloc", to get the position
subject = df.iloc[:, 1:5]
df["Sum"] = subject.sum(axis=1)

In [21]:
df.head(3)

,Candidate_Name,English,Mathematics,Physics,Chemistry,Total,Average,Sum
0,Amina Nwosu,45,89,66,57,257,64.25,257
1,Oluwaseun Okafor,64,74,75,61,274,68.50,274
2,Tunde Okafor,50,48,61,75,234,58.50,234

In [25]:
test= df.iloc[0:2, 1:5]
df["test"] = test.sum(axis=1)
df.head()

,Candidate_Name,English,Mathematics,Physics,Chemistry,Total,Average,Sum,test
0,Amina Nwosu,45,89,66,57,257,64.25,257,257.0
1,Oluwaseun Okafor,64,74,75,61,274,68.50,274,274.0
2,Tunde Okafor,50,48,61,75,234,58.50,234,NaN
3,Tunde Lawal,55,50,40,97,242,60.50,242,NaN
4,Paul Balogun,96,78,64,44,282,70.50,282,NaN

In [27]:
# Df.drop is use in pandas to delete a column ,
df.drop("Sum", axis =1, inplace = True)
df.drop("test", axis = 1, inplace = True)

In [28]:
df.head()

     Candidate_Name  English  Mathematics  Physics  Chemistry  Total  Average
0       Amina Nwosu       45           89       66         57    257    64.25
1  Oluwaseun Okafor       64           74       75         61    274    68.50
2      Tunde Okafor       50           48       61         75    234    58.50
3       Tunde Lawal       55           50       40         97    242    60.50
4      Paul Balogun       96           78       64         44    282    70.50

In [30]:
# Calculating the overall best student in Jamb
# iloc is use for integer and index, while loc is use for name(label) and string
highest_score_index = df["Total"].idxmax()
best_student = df.loc[highest_score_index]
print(best_student)

Candidate_Name    Joy Bello
English                  97
Mathematics              88
Physics                 100
Chemistry                95
Total                   380
Average                95.0
Name: 1007, dtype: object

In [32]:
# specify the columns you want to print/display
# Note that if you are trying to display more than one column you have to use double square bracket[[]]
print(best_student[["Candidate_Name", "Total"]] )

Candidate_Name    Joy Bello
Total                   380
Name: 1007, dtype: object

In [33]:
print(f"The overall best student is {best_student["Candidate_Name"]} with the total score of {best_student["Total"]}")

 The overall best student is Joy Bello with the total score of 380

In [39]:
# Overall Top 10 students with the highest scores
# First method
top_students = df.sort_values("Total", ascending= False)
top_students.head(10)

,Candidate_Name,English,Mathematics,Physics,Chemistry,Total,Average
1007,Joy Bello,97,88,100,95,380,95.00
882,Janet Ibrahim,95,95,95,91,376,94.00
334,Segun Obi,92,100,89,93,374,93.50
1188,Ibrahim Afolabi,88,100,96,86,370,92.50
1036,Emmanuel Afolabi,85,98,90,92,365,91.25
780,Amina Akinyemi,96,75,95,98,364,91.00
998,Ibrahim Obi,79,97,90,94,360,90.00
1116,Tunde Nnamdi,83,85,96,95,359,89.75
346,Ifeanyi Lawal,92,97,78,92,359,89.75
1186,Yusuf Ajayi,100,98,94,67,359,89.75

In [40]:
# Second method, Top 5
top_students = df.nlargest(5, "Total")
top_students

,Candidate_Name,English,Mathematics,Physics,Chemistry,Total,Average
1007,Joy Bello,97,88,100,95,380,95.00
882,Janet Ibrahim,95,95,95,91,376,94.00
334,Segun Obi,92,100,89,93,374,93.50
1188,Ibrahim Afolabi,88,100,96,86,370,92.50
1036,Emmanuel Afolabi,85,98,90,92,365,91.25

In [44]:
# student that score less than 200
df[df["Total"] < 200]

,Candidate_Name,English,Mathematics,Physics,Chemistry,Total,Average
93,Emeka Bello,42,46,49,54,191,47.75
168,Tunde Obi,54,42,51,48,195,48.75
239,Ruth Obi,43,55,41,56,195,48.75
331,Chinedu Onyeka,49,47,49,51,196,49.00
414,Joy Bello,43,40,68,42,193,48.25
552,Emmanuel Ajayi,58,43,42,53,196,49.00
602,Ngozi Ajayi,52,41,43,43,179,44.75
643,Tunde Eze,42,44,41,66,193,48.25
660,Oluwaseun Nnamdi,50,55,51,42,198,49.50
701,Grace Lawal,47,59,41,41,188,47.00
879,Grace Adeyemi,40,43,63,51,197,49.25
915,Ifeanyi Nnamdi,45,50,49,45,189,47.25

In [51]:
# Calculate the overall best student in English
best_english_score = df["English"].max()
best_scores = df[df["English"] ==  best_english_score]
best_scores[["Candidate_Name", "English"]]

       Candidate_Name  English
56     Kelechi Okafor      100
73     Ibrahim Yakubu      100
120    Zainab Ibrahim      100
177       Sade Yakubu      100
249          Musa Eze      100
514   Goodluck Onyeka      100
581         Grace Eze      100
857     David Danjuma      100
890    Esther Adeleke      100
1033    Ibrahim Ajayi      100
1094    Segun Danjuma      100
1161      Chinedu Obi      100
1186      Yusuf Ajayi      100

In [46]:
print(best_english_score)

100

In [52]:
# Calculate the overall best student in Mathematics
best_math_score = df["Mathematics"].max()
best_scores = df[df["Mathematics"] ==  best_math_score]
best_scores[["Candidate_Name", "Mathematics"]]

       Candidate_Name  Mathematics
41     Goodluck Okeke          100
132        Paul Lawal          100
180       Joy Adeleke          100
334         Segun Obi          100
546   Segun Abdullahi          100
669      Precious Ojo          100
716     Amina Adeleke          100
761      Musa Danjuma          100
814     Chinedu Aliyu          100
836          Paul Obi          100
839   Favour Mohammed          100
848    Tunde Akinyemi          100
864      Fatima Lawal          100
875        Uche Lawal          100
889    Mercy Mohammed          100
929    Favour Adeyemi          100
936     Tunde Adeyemi          100
1113      Sade Okafor          100
1188  Ibrahim Afolabi          100
1197       Adaobi Eze          100

In [53]:
# Calculate the overall best student in Physics
best_physics_score = df["Physics"].max()
best_scores = df[df["Physics"] ==  best_physics_score]
best_scores[["Candidate_Name", "Physics"]]

       Candidate_Name  Physics
133     Yusuf Balogun      100
143       Mary Yakubu      100
153      Janet Nnamdi      100
301       Mercy Nwosu      100
503    Precious Nwosu      100
522   Adebayo Afolabi      100
568      Ruth Adeyemi      100
569    Blessing Okeke      100
609     Emeka Adeyemi      100
1000     Precious Obi      100
1007        Joy Bello      100
1039      Chinedu Obi      100
1057  Chinedu Ibrahim      100
1060    Chisom Nnamdi      100
1098   Yusuf Akinyemi      100
1124   Ifeanyi Onyeka      100
1148    Adaobi Nnamdi      100

In [54]:
# Calculate the overall best student in Chemistry
best_student_chemistry = df["Chemistry"].max()
best_scores = df[df["Chemistry"] ==  best_student_chemistry]
best_scores[["Candidate_Name", "Chemistry"]]

        Candidate_Name  Chemistry
59         Joy Afolabi        100
79      Kelechi Onyeka        100
159      Esther Onyeka        100
170         Paul Ajayi        100
279        Amina Okeke        100
324       Uche Ibrahim        100
356         Zainab Eze        100
364      Daniel Okafor        100
388      Esther Okafor        100
546    Segun Abdullahi        100
567        Uche Nnamdi        100
583   Oluwaseun Yakubu        100
592       Yusuf Nnamdi        100
649     Goodluck Bello        100
737   Oluwaseun Okafor        100
743        Tunde Nwosu        100
899   Goodluck Adeyemi        100
1048        Daniel Obi        100
1058   Kelechi Ibrahim        100
1079       Ibrahim Obi        100